export const FETCH_PHOTOS_LOADING = 'FETCH_PHOTOS_LOADING';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';

export const SINGLE_PHOTO_LOADING = 'SINGLE_PHOTO_LOADING';
export const SINGLE_PHOTO_SUCCESS = 'SINGLE_PHOTO_SUCCESS';
export const SINGLE_PHOTO_FAILUR = 'SINGLE_PHOTO_FAILUR';

export const FILTER_PHOTO_LOADING = 'FILTER_PHOTO_LOADING';
export const FILTER_PHOTO_SUCCESS = 'FILTER_PHOTO_SUCCESS';
export const FILTER_PHOTO_FAILUR = 'FILTER_PHOTO_FAILUR';

export const FILTER_START_DATE = 'FILTER_START_DATE';
export const FILTER_END_DATE = 'FILTER_END_DATE';
